### ISSUE TITLE
Détailler le README

### ISSUE THREAD

**Issue by Delthas** [Armand-Touminet/mo101-agile-tdd-clone#1]
Bonjour, est-ce que tu peux préciser le README s'il te plaît. Je ne comprends pas très bien ton projet. Merci. La bises, Françoise.

**Comment by Armand-Touminet** [comment]
Je ne suis pas contre, mais cela nécessiterai une nouvelle RFC.

**Comment by Delthas** [comment]
D'accord, je fais une Pull Request !

La bise, Françoise.
